[package]
name = "plugin_template"
version = "0.1.0"
edition = "2024"

[lib]
name = "template"
crate-type = ["cdylib",'rlib']

[dependencies]
abi_stable = "*"
interface = { path = "../interface" }
async-ffi = { version = "*", features = ["abi_stable", "macros"] }

